exports.USER_ROLES = {
    USER: "USER",
    DELIVARY_BOY: "DELIVARY_BOY",
    RESTURANT: "RESTURANT",
    ADMIN: "ADMIN",
};

exports.ORDER_STATUS = {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    PREPARING: "PREPARING",
    PARTIALLY_DELIIVARED: "PARTIALLY_DELIVARED",
    COMPLETED: "COMPLETED",
    CANCELED: "CANCELED",
};
